trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      name: rweritz/CICD
      endpoint: rweritz

steps:
  - template: pipeline-templates/dotnet-ci-template.yml@templates
    parameters:
      restoreFeed: excribe
      publishFeed: excribe