trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: CICD
      type: github
      name: rweritz/CICD
      endpoint: rweritz

jobs:
  - template: dotnet-ci-pipeline.yml@CICD
    parameters:
      restoreFeed: excribe
      publishFeed: excribe