trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      name: rweritz/CICD
      endpoint: GitHub

jobs:
  - template: dotnet-ci-pipeline.yml@templates
    parameters:
      restoreFeed: excribe
      publishFeed: excribe