trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-20.04'

resources:
  repositories:
    - repository: templates
      type: github
      name: rweritz/CICD
      endpoint: rweritz

variables:
  GitVersion.SemVer: ''

steps:
  - template: pipeline-templates/dotnet-ci-template.yml@templates
    parameters:
      restoreFeed: excribe
      publishFeed: excribe